### ISSUE TITLE
Error while executing build-administration

### ISSUE THREAD

**Issue by JonasVanelstlande** [dotmailer/dotdigital-for-shopware-flowbuilder#1]
When I run the build-administration.sh command I get a JS syntax error in the validation-directive.js
The experimental classProperties of Babel are not active in Shopware
The version of Shopware is 6.4.9, which you claim you support version 6.4
I have tried installing the babel/plugin-proposal-class-properties, but I still get the same error

Screenshot of the error:
![Screenshot 2023-03-29 at 15 57 07](https://user-images.githubusercontent.com/121869153/228562446-2f05ca87-a922-457d-9716-196eaeb71313.png)

**Comment by sta1r** [comment]
@JonasVanelstlande apologies this has been overlooked. Will investigate.

**Comment by sta1r** [comment]
Fixed in https://github.com/dotmailer/dotdigital-for-shopware-flowbuilder/releases/tag/v1.1.1.
